---
title: "Lab1"
author: "Jason Chen"
date: "2024-08-23"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Task 1
  getwd()

# Task 2
  ddt <- read.csv("DDT-1.csv")
  
  head(ddt)

# Task 3
## 3.1
  summary(ddt)
  
  Qualitative: RIVER, SPECIES

## 3.2
  Quantitative: MILE, LENGTH, WEIGHT, DDT
  
## 3.3
  with(ddt, unique(SPECIES))

  There are 3 SPECIES in the ddt data set
  
## 3.4
  library(dplyr)
  
  bass <- ddt %>% filter(SPECIES=="LMBASS")
  
  vector <- bass %>% filter(WEIGHT > 800)
  
  vector
  
## 3.5
  scm <- ddt %>% filter(RIVER=="SCM")
  
  vector2 <- scm %>% filter(DDT > 4)

  vector2

# Task 4

## 4.1
  mean(with(ddt, LENGTH))
  
  Mean LENGTH = 42.8125
  
## 4.2
  sd(with(ddt, WEIGHT))

  Standard Deviation of WEIGHT = 376.5461
  
## 4.3
  library(ggplot2)

  plot(WEIGHT~LENGTH, ddt)

  plot(LENGTH~WEIGHT, ddt)

  Answer = 0

## 4.4
  v=1:20
  
  v
  
  v/20
  
  Last value of v/20 is 1
  
# Task 5
  riverT=with(ddt, table(RIVER))
  riverT
  
  barplot(riverT, col=1:4)

  crossT = with(ddt, table(SPECIES, RIVER))
  crossT
  
  barplot(crossT)
  
# Task 6
  fishT = with(ddt, table(SPECIES))
  pie(fishT)
  
  pie(riverT, col=1:4)
  
# Task 7
  boxplot(DDT~SPECIES, col="Blue", data=ddt)

  boxplot(WEIGHT~SPECIES, col="Red", data=ddt)
  
  boxplot(LENGTH~SPECIES, col="Blue", data=ddt)
  
# Task 8
  rivcol=with(ddt, ifelse(RIVER=="FCM","Red",
                      ifelse(RIVER=="LCM","Blue",
                          ifelse(RIVER=="SCM","Green","Black"))))

  coplot(LENGTH~WEIGHT|RIVER, data=ddt, col=rivcol)

  fishcol=with(ddt,ifelse(SPECIES=="CCATFISH","Red",
                      ifelse(SPECIES=="SMBUFFALO","Blue","Green")))

  coplot(DDT~WEIGHT|SPECIES, data=ddt, col=fishcol)

# Task 9

## Boxplot
  b = ggplot(ddt, aes(x = SPECIES, y = WEIGHT)) + 
  geom_boxplot(aes( fill = RIVER)) + labs(title="Jason Chen")
  
  b
  
## Violinplot
  v = ggplot(ddt, aes(x = RIVER, y = LENGTH)) +
  geom_violin(aes( fill = SPECIES)) + labs(title="Jason Chen")
  
  v

## Scatterpot
  g = ggplot(ddt, aes(x = WEIGHT, y = LENGTH )) + 
  geom_point(aes( color = SPECIES)) + labs(title="Jason Chen")

  g

